name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build the project with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Deploy to Production Server
        env:
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          HOST: ${{ secrets.SERVER_HOST }}
          PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        run: |
          scp -i $PRIVATE_KEY target/*.jar $USERNAME@$HOST:/path/to/deploy/
          ssh -i $PRIVATE_KEY $USERNAME@$HOST "cd /path/to/deploy && ./restart-app.sh"
